# Generated by Django 3.2.16 on 2023-01-24 20:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='default_profile_image.png', max_length=255, verbose_name='image'),
        ),
    ]
